<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1LE36FS" name="test4Demo" tests="6" failures="1" timestamp="19 Aug 2019 02:31:43 GMT" time="1.689" errors="0">
  <testcase name="runScenario" time="1.336" classname="sence.createServerTest"/>
  <testcase name="runScenario" time="0.054" classname="sence.createServerTest"/>
  <testcase name="runScenario" time="0.012" classname="sence.loginTest"/>
  <testcase name="runScenario" time="0.011" classname="sence.loginTest"/>
  <testcase name="runScenario" time="0.014" classname="sence.loginTest"/>
  <testcase name="runScenario" time="0.027" classname="sence.loginTest">
    <failure type="org.test4j.spec.exceptions.ScenarioAssertError" message="04 - case5:输入错误密码123
 throw an exception:
java.lang.RuntimeException: Invoke class (sence.loginTest.java:1) method[checkMsg] error:
Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]!
java.lang.RuntimeException: Invoke class (sence.loginTest.java:1) method[checkMsg] error:
Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]!
	at org.test4j.spec.JSpecExecutorFactory.runSingleStep(JSpecExecutorFactory.java:216)
	at org.test4j.spec.JSpecExecutorFactory.runScenario(JSpecExecutorFactory.java:178)
	at org.test4j.testng.JSpec.run(JSpec.java:75)
	at sence.loginTest.runScenario(loginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.test4j.testng.Test4JHookable.run(Test4JHookable.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.RuntimeException: Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at org.test4j.spec.scenario.step.SpecMethod.execute(SpecMethod.java:98)
	at org.test4j.spec.JSpecExecutorFactory.runSingleStep(JSpecExecutorFactory.java:210)
	... 37 more
Caused by: java.lang.RuntimeException: java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at org.test4j.tools.commons.ExceptionWrapper.wrapWithRuntimeException(ExceptionWrapper.java:106)
	at org.test4j.tools.reflector.MethodAccessor.invokeUnThrow(MethodAccessor.java:75)
	at org.test4j.spec.scenario.step.SpecMethod.execute(SpecMethod.java:93)
	... 38 more
Caused by: java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at sence.loginTest.checkMsg(loginTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.test4j.tools.reflector.MethodAccessor.invoke(MethodAccessor.java:49)
	at org.test4j.tools.reflector.MethodAccessor.invokeUnThrow(MethodAccessor.java:72)
	... 39 more

04 - case5:输入错误密码123 throw errors at:">
      <![CDATA[org.test4j.spec.exceptions.ScenarioAssertError: 04 - case5:输入错误密码123
 throw an exception:
java.lang.RuntimeException: Invoke class (sence.loginTest.java:1) method[checkMsg] error:
Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]!
java.lang.RuntimeException: Invoke class (sence.loginTest.java:1) method[checkMsg] error:
Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]!
	at org.test4j.spec.JSpecExecutorFactory.runSingleStep(JSpecExecutorFactory.java:216)
	at org.test4j.spec.JSpecExecutorFactory.runScenario(JSpecExecutorFactory.java:178)
	at org.test4j.testng.JSpec.run(JSpec.java:75)
	at sence.loginTest.runScenario(loginTest.java:23)
	at org.test4j.testng.Test4JHookable.run(Test4JHookable.java:56)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.RuntimeException: Invoke spec method[checkMsg] error:java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at org.test4j.spec.scenario.step.SpecMethod.execute(SpecMethod.java:98)
	at org.test4j.spec.JSpecExecutorFactory.runSingleStep(JSpecExecutorFactory.java:210)
	... 37 more
Caused by: java.lang.RuntimeException: java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at org.test4j.tools.commons.ExceptionWrapper.wrapWithRuntimeException(ExceptionWrapper.java:106)
	at org.test4j.spec.scenario.step.SpecMethod.execute(SpecMethod.java:93)
	... 38 more
Caused by: java.lang.AssertionError: expected [用户名不存在！] but found [密码不正确！]
	at sence.loginTest.checkMsg(loginTest.java:55)
	... 39 more

04 - case5:输入错误密码123 throw errors at:
	at org.test4j.spec.JSpecExecutorFactory.runScenario(JSpecExecutorFactory.java:191)
	at org.test4j.testng.JSpec.run(JSpec.java:75)
	at sence.loginTest.runScenario(loginTest.java:23)
	at org.test4j.testng.Test4JHookable.run(Test4JHookable.java:56)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- test4Demo -->
